spring.application.name=Datastore
server.port=8081
server.address=192.168.1.247
server.security_token=SOME_TOKEN

# Mongo
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ndsv2
spring.data.mongodb.uuid-representation=standard